In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('shoe.csv')

In [3]:
df.head()

size(cm) class(y)
0     9.500   Female
1    10.125     Male
2    10.410     Male
3     9.810   Female
4    11.050     Male

In [4]:
df.shape

(40, 2)

In [5]:
df['class(y)'].value_counts()

class(y)
Male      22
Female    18
Name: count, dtype: int64

# Label Encoder

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [7]:
df['class(y)'] = le.fit_transform(df[['class(y)']])
df.head()

size(cm)  class(y)
0     9.500         0
1    10.125         1
2    10.410         1
3     9.810         0
4    11.050         1

In [8]:
df.head()

size(cm)  class(y)
0     9.500         0
1    10.125         1
2    10.410         1
3     9.810         0
4    11.050         1

In [9]:
x=df.drop('class(y)', axis=1)

In [10]:
y=df[['class(y)']]

In [11]:
x.head()

size(cm)
0     9.500
1    10.125
2    10.410
3     9.810
4    11.050

In [12]:
y.head()

class(y)
0         0
1         1
2         1
3         0
4         1

# Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
reg = LogisticRegression()

In [15]:
reg.fit(x,y)

LogisticRegression()

In [16]:
reg.coef_

array([[2.62699981]])

In [17]:
reg.intercept_

array([-26.18198935])

In [18]:
import numpy as np
np.array(df['class(y)'])

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1])

In [19]:
reg.predict(x) # predicted

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0])

In [20]:
x.head()

size(cm)
0     9.500
1    10.125
2    10.410
3     9.810
4    11.050

In [21]:
reg.predict_proba(x)

array([[0.77302845, 0.22697155],
       [0.39738242, 0.60261758],
       [0.2377457 , 0.7622543 ],
       [0.6013567 , 0.3986433 ],
       [0.05486986, 0.94513014],
       [0.8951951 , 0.1048049 ],
       [0.79524583, 0.20475417],
       [0.17003227, 0.82996773],
       [0.66235827, 0.33764173],
       [0.69665958, 0.30334042],
       [0.59504263, 0.40495737],
       [0.23301782, 0.76698218],
       [0.35729164, 0.64270836],
       [0.07737361, 0.92262639],
       [0.17757582, 0.82242418],
       [0.11860381, 0.88139619],
       [0.46492055, 0.53507945],
       [0.52395197, 0.47604803],
       [0.29398481, 0.70601519],
       [0.16274575, 0.83725425],
       [0.38176611, 0.61823389],
       [0.83473184, 0.16526816],
       [0.88221669, 0.11778331],
       [0.1392146 , 0.8607854 ],
       [0.71305157, 0.28694843],
       [0.21476669, 0.78523331],
       [0.2994667 , 0.7005333 ],
       [0.09833362, 0.90166638],
       [0.2192301 , 0.7807699 ],
       [0.11860381, 0.88139619],
       [0.

In [22]:
reg.score(x,y)

0.925